"""New2


Revision ID: 030e15e6426b
Revises: d4e1585afa5a
Create Date: 2023-11-29 14:44:30.463877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '030e15e6426b'
down_revision = 'd4e1585afa5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('like_count', sa.Integer(), nullable=True))
        batch_op.drop_column('likes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.INTEGER(), nullable=True))
        batch_op.drop_column('like_count')

    # ### end Alembic commands ###
