"""New


Revision ID: d4e1585afa5a
Revises: 41ea852e2f94
Create Date: 2023-11-29 14:21:11.915794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4e1585afa5a'
down_revision = '41ea852e2f94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_table', schema=None) as batch_op:
        batch_op.drop_column('likes')

    # ### end Alembic commands ###
